/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.TbModelosCxP;

/**
 *
 * @author Ryzen5
 */
public class FrmConsulta extends javax.swing.JFrame {
    public TbModelosCxP modelo = new TbModelosCxP();
    /**
     * Creates new form FrmConsulta
     */
    public FrmConsulta() {
        initComponents();
    }

    public void iniciaTabla(){
        modelo.inicializaTabla(tbCuentasPorPagar,0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCuentasPorPagar = new javax.swing.JTable();
        lbTitulo = new javax.swing.JLabel();
        menuBarCxP = new javax.swing.JMenuBar();
        menuIEmpleado = new javax.swing.JMenu();
        menuIAsalariado = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuIFactura = new javax.swing.JMenuItem();
        menuISalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbCuentasPorPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCuentasPorPagar);

        lbTitulo.setText("Cuentas por pagar");

        menuIEmpleado.setText("Empleado");

        menuIAsalariado.setText("Asalariado");
        menuIAsalariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIAsalariadoActionPerformed(evt);
            }
        });
        menuIEmpleado.add(menuIAsalariado);

        menuBarCxP.add(menuIEmpleado);

        jMenu4.setText("Factura");

        menuIFactura.setText("Factura");
        menuIFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIFacturaActionPerformed(evt);
            }
        });
        jMenu4.add(menuIFactura);

        menuISalir.setText("Salir");
        menuISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuISalirActionPerformed(evt);
            }
        });
        jMenu4.add(menuISalir);

        menuBarCxP.add(jMenu4);

        setJMenuBar(menuBarCxP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuISalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuISalirActionPerformed

    private void menuIAsalariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIAsalariadoActionPerformed
        // TODO add your handling code here:
        modelo.inicializaTabla(tbCuentasPorPagar, 2);
    }//GEN-LAST:event_menuIAsalariadoActionPerformed

    private void menuIFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIFacturaActionPerformed
        // TODO add your handling code here:
        modelo.inicializaTabla(tbCuentasPorPagar, 1);
    }//GEN-LAST:event_menuIFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenuBar menuBarCxP;
    private javax.swing.JMenuItem menuIAsalariado;
    private javax.swing.JMenu menuIEmpleado;
    private javax.swing.JMenuItem menuIFactura;
    private javax.swing.JMenuItem menuISalir;
    private javax.swing.JTable tbCuentasPorPagar;
    // End of variables declaration//GEN-END:variables
}
